app = "time-tracker-app"
primary_region = "yyz"

[build]
  dockerfile = "Dockerfile"

  [build.args]
    NUXT_PUBLIC_API_BASE = "https://api.timetracker.space"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
