# fly.toml app configuration file generated for timetracker-api-lqdb8q on 2026-05-17T16:30:57Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'timetracker-api-lqdb8q'
primary_region = 'yyz'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = 'php artisan migrate --force'

[env]
  APP_ENV = 'production'
  BROWSERSHOT_CHROMIUM_PATH = '/usr/bin/chromium-browser'
  LOG_CHANNEL = 'stderr'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
