# fly.toml app configuration file generated for timetracker-api-lqdb8q on 2026-05-18T02:34:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "timetracker-api-lqdb8q"
primary_region = "yyz"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "php artisan migrate --force"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  BROWSERSHOT_CHROMIUM_PATH = "/usr/bin/chromium-browser"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "30s"
    interval = "30s"
    method = "GET"
    timeout = "10s"
    path = "/api/health"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
